### ISSUE TITLE
Pimcore 11 - not able to get definitions properly saved/added/executed

### ISSUE THREAD

**Issue by ITspirit** [w-vision/DataDefinitions#400]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Branch?          | 4.1.3

Has anyone DataDefinitons sucessfull running with Pimcore 11?

Had some strange behaviors:

I used this config (as in the bundle):

 ``` 
data_definitions:
    config_location:
        import_definitions:
            write_target:
                type: 'settings-store'
        export_definitions:
            write_target:
                type: 'settings-store'
 ``` 

But every time i create an "Export" or "Import" definition, it appears on both tabs. No difference for the system.

In the database table it looks (should be an Export) like this:
![image](https://github.com/w-vision/DataDefinitions/assets/2453696/4ca6c3f3-5e9f-46ee-9511-69c7419fee64)

And on the "Import Definitions" Tab the "(+) Add" Button is disabled, however on the Export Definitions Tab it is enabled.

Any hints what i am doing wrong?

Or is DataDefinitons still not ready for Pimcore 11 or did i missunderstood something?
