### ISSUE TITLE
Persister tags not loaded properly

### ISSUE THREAD

**Issue by Robert-Jankiewicz-weg** [w-vision/DataDefinitions#441]
When creating a definition for a persister according to the docs, i.e.:
```yaml
    app.data_definitions.url_persister:
        class: App\DataDefinitions\Persister\UrlPersister
        tags:
            - { name: data_definitions.persister, type: url-persister }
```

It leads to both "url_persister" and "url-persister" being visible in the dropdown:

![Image](https://github.com/user-attachments/assets/03820c76-7d0a-4fad-a2e2-f5d18d240f13)

Service info:
```bash
Information for Service "app.data_definitions.url_persister"
==================================================================

 ---------------- -------------------------------------------------- 
  Option           Value                                             
 ---------------- -------------------------------------------------- 
  Service ID       app.data_definitions.url_persister          
  Class            App\DataDefinitions\Persister\UrlPersister        
  Tags             data_definitions.persister (type: url-persister)  
                   data_definitions.persister                        
  Public           no                                                
  Synthetic        no                                                
  Lazy             no                                                
  Shared           yes                                               
  Abstract         no                                                
  Autowired        yes                                               
  Autoconfigured   yes                                               
  Usages           data_definitions.registry.persister               
 ---------------- -------------------------------------------------- 
```

However, when one tries to change the tag name to "url_persister", an error occurs:
```bash
In ServiceRegistry.php line 39:
                                                                        
  Import Definition Persisters of type "url_persister" already exists.                                                                       
```
...that leads to all imports being impossible to run.

**Comment by dpfaffenbauer** [comment]
disable autoconfiguration for the service:

```
app.data_definitions.url_persister:
        class: App\DataDefinitions\Persister\UrlPersister
        autoconfigure: false
        tags:
            - { name: data_definitions.persister, type: url-persister }
```
